# Start from Ubuntu 22 base image
FROM ubuntu:22.04

# Install MongoDB dependencies
RUN apt-get update && apt-get install -y \
    gnupg \
    wget \
    && rm -rf /var/lib/apt/lists/*

# Install MongoDB
RUN \
  wget -qO - "https://pgp.mongodb.com/server-6.0.asc" | gpg -o /usr/share/keyrings/mongodb-server-6.0.gpg --dearmor && \
  echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-6.0.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0 multiverse" | tee "/etc/apt/sources.list.d/mongodb-org-6.0.list" && \
  apt update && apt -y install mongodb-org
  
# Create dir Mongo
RUN mkdir -p /data/db
RUN chown mongodb:mongodb /data/db

# Define mountable directories.
VOLUME ["/data/db"]

# Expose the MongoDB port
EXPOSE 27017

# Command to start MongoDB
CMD ["mongod"]
