# Start from a ubuntu based image 
FROM ubuntu:22.04

# Install Python and pip
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /app

# Install data science libraries
COPY requirements.txt ./
RUN pip3 install -r requirements.txt
# Command to start the Python environment
CMD ["python3"]