# Start from Ubuntu 22 base image
FROM ubuntu:22.04

# Install MongoDB dependencies
RUN apt-get update && apt-get install -y \
    gnupg \
    wget \
    && rm -rf /var/lib/apt/lists/*

# Install libssl1.1
RUN apt-get update && apt-get install -y \
    libssl1.1 \
    && rm -rf /var/lib/apt/lists/*

# Install MongoDB
RUN wget -qO - https://www.mongodb.org/static/pgp/server-5.0.asc | apt-key add - \
    && echo "deb http://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/5.0 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-5.0.list \
    && apt-get update \
    && apt-get install -y \
    mongodb-org \
    && rm -rf /var/lib/apt/lists/*

# Expose the MongoDB port
EXPOSE 27017

# Command to start MongoDB
CMD ["mongod"]
